baseURL = "https://a-p-n.github.io"
title = "___apn___"
languageCode = "en"
DefaultContentLanguage = "en" # Change this to change the site's language
theme = "hugo.386"
preserveTaxonomyNames = true

[params]
    # The name to display as main title in the home page
    mainpagetitle = "APN's BLOG!"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "Welcome to my BLOG!"

    # The description of your website. It will be displayed in the home page
    mainpagedesc = "This is my personal blog where I post all the writeups. Check the links below to access the posts."

    # The name to display in the copyright section in the footer
    copyrightname = "Adithyan Pratheeksh Nair"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    # copyrighturl = "http://jmf-portfolio.netlify.com"

    # Show the "built on Hugo" disclaimer
    showhugo = true

    # Urls for social networks
    github = "https://github.com/a-p-n/"
    twitter = "https://x.com/@adithyanPn0"

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = false

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 1.0

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = true

[params.copyright]
    name = "Adithyan Pratheeksh Nair"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    # url = "http://jmf-portfolio.netlify.com"

    # Text to go before copyright information
    # prefix = "[hugo.386 theme by Max le Fou](https://gitlab.com/maxlefou/hugo.386)"

    # Text to go between copyright and hugo disclaimer (if enabled)
    # suffix = "Example site"

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "About"       # A display name for the button
    url = "/about"       # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"       # The path can lead to a content folder too.
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    tabWidth = 4

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
